name: Build and Export Windows .exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.10

    - name: Create Short Path for vcpkg
      run: |
        subst X: C:\vcpkg
        mkdir X:\src

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git X:\src\vcpkg
        X:\src\vcpkg\bootstrap-vcpkg.bat

    - name: Clean vcpkg Build Artifacts and Update
      shell: pwsh
      run: |
        $Paths = @("X:\src\vcpkg\buildtrees\boost-cobalt", "X:\src\vcpkg\packages\boost-cobalt_x64-windows", "X:\src\vcpkg\installed\boost-cobalt")
        foreach ($Path in $Paths) {
          if (Test-Path -Path $Path) {
            Remove-Item -Recurse -Force $Path
          }
        }
        X:\src\vcpkg\vcpkg.exe update

    - name: Install Dependencies using vcpkg
      run: X:\src\vcpkg\vcpkg.exe install qt5 jsoncpp boost

    - name: Configure CMake with vcpkg Toolchain (Release)
      run: |
        cmake -G "Visual Studio 16 2019" ^
          -A x64 ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_TOOLCHAIN_FILE=X:/src/vcpkg/scripts/buildsystems/vcpkg.cmake ^
          -DCMAKE_PREFIX_PATH=X:/src/vcpkg/installed/x64-windows ^
          .

    - name: Build the Project (Release Configuration)
      run: cmake --build . --config Release -- -v

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CommandAliasManager-Executable
        path: ./Release/CommandAliasManager.exe

    - name: Upload Boost-Cobalt Build Logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: boost-cobalt-debug-logs
        path: X:/src/vcpkg/buildtrees/boost-cobalt/*.log
