name: Build and Export Windows .exe
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.10
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
    - name: Install Dependencies using vcpkg
      run: |
        .\vcpkg\vcpkg.exe install qt5 jsoncpp boost
    - name: Configure CMake with vcpkg Toolchain
      run: cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake .
    - name: Build the Project
      run: cmake --build . --config Release
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CommandAliasManager-Executable
        path: ./Release/CommandAliasManager.exe
