name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies with vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        Remove-Item Env:\VCPKG_ROOT
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe update
        .\vcpkg.exe install qt5-base:x64-windows boost-filesystem:x64-windows jsoncpp:x64-windows

    - name: Configure CMake
      run: cmake -S CommandAliasManager -B build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
