name: Build and Export Windows .exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.10

    - name: Create Short Path for vcpkg
      run: |
        subst X: C:\vcpkg
        mkdir X:\src

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git X:\src\vcpkg
        X:\src\vcpkg\bootstrap-vcpkg.bat

    - name: Clean vcpkg Build Artifacts
      # Clean existing build artifacts to ensure a fresh rebuild
      run: |
        rmdir /s /q X:\src\vcpkg\buildtrees\boost-cobalt
        rmdir /s /q X:\src\vcpkg\packages\boost-cobalt_x64-windows
        rmdir /s /q X:\src\vcpkg\installed\boost-cobalt
        X:\src\vcpkg\vcpkg.exe update

    - name: Install Dependencies using vcpkg
      # Switch to using the regular boost package instead of boost-cobalt
      run: X:\src\vcpkg\vcpkg.exe install qt5 jsoncpp boost

    - name: Configure CMake with vcpkg Toolchain (Release)
      # Use Release mode instead of Debug to avoid configuration issues
      run: cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=X:/src/vcpkg/scripts/buildsystems/vcpkg.cmake .

    - name: Build the Project (Release Configuration)
      # Build the project using CMake with the Release configuration
      run: cmake --build . --config Release -- -v

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CommandAliasManager-Executable
        path: ./Release/CommandAliasManager.exe

    - name: Upload Boost-Cobalt Build Logs
      # Upload the build logs as artifacts if the build fails
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: boost-cobalt-debug-logs
        path: X:/src/vcpkg/buildtrees/boost-cobalt/*.log