name: Build and Export Windows .exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.10

    - name: Install Dependencies
      run: |
        choco install -y qt5 boost-msvc-14.1
        choco install -y jsoncpp

    - name: Configure CMake
      run: cmake -G "Visual Studio 16 2019" .

    - name: Build
      run: cmake --build . --config Release

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CommandAliasManager-Executable
        path: ./Release/CommandAliasManager.exe