name: Build and Export Windows .exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.10

    - name: Create Short Path for vcpkg
      run: |
        subst X: C:\vcpkg
        mkdir X:\src

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git X:\src\vcpkg
        X:\src\vcpkg\bootstrap-vcpkg.bat

    - name: Clean Existing vcpkg Build Artifacts
      # Check if directories exist before attempting to remove them
      shell: pwsh
      run: |
        X:\src\vcpkg\vcpkg.exe remove boost-cobalt --recurse
        if (Test-Path -Path X:\src\vcpkg\buildtrees\boost-cobalt) {
          Remove-Item -Recurse -Force X:\src\vcpkg\buildtrees\boost-cobalt
        }
        if (Test-Path -Path X:\src\vcpkg\packages\boost-cobalt_x64-windows) {
          Remove-Item -Recurse -Force X:\src\vcpkg\packages\boost-cobalt_x64-windows
        }
        if (Test-Path -Path X:\src\vcpkg\installed\boost-cobalt) {
          Remove-Item -Recurse -Force X:\src\vcpkg\installed\boost-cobalt
        }
        X:\src\vcpkg\vcpkg.exe update
        X:\src\vcpkg\vcpkg.exe install qt5 jsoncpp boost

    - name: Configure CMake with vcpkg Toolchain (Release)
      run: cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=X:/src/vcpkg/scripts/buildsystems/vcpkg.cmake .

    - name: Build the Project (Release Configuration)
      run: cmake --build . --config Release -- -v

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CommandAliasManager-Executable
        path: ./Release/CommandAliasManager.exe