name: Build and Export Windows .exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Use windows-2019 for better compatibility with Visual Studio 2019
    runs-on: windows-2019

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.10

    - name: Create Short Path for vcpkg
      run: |
        subst X: C:\vcpkg
        mkdir X:\src

    - name: Install vcpkg
      # Install vcpkg in the virtual drive to avoid path length issues
      run: |
        git clone https://github.com/microsoft/vcpkg.git X:\src\vcpkg
        X:\src\vcpkg\bootstrap-vcpkg.bat

    - name: Update vcpkg and Install Dependencies
      # Update vcpkg and install dependencies using the latest ports
      run: |
        git -C X:\src\vcpkg pull
        X:\src\vcpkg\vcpkg.exe update
        X:\src\vcpkg\vcpkg.exe install qt5 jsoncpp boost

    - name: Configure CMake with vcpkg Toolchain
      # Specify the toolchain file using the shortened path
      run: cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=X:/src/vcpkg/scripts/buildsystems/vcpkg.cmake .

    - name: Build the Project with Verbose Output
      # Build the project using CMake with verbose logging
      run: cmake --build . --config Release --verbose

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CommandAliasManager-Executable
        path: ./Release/CommandAliasManager.ex